# Config for the friends command.

# MySQL server config
mysql-data:
  user: sqlUser
  password: sqlPassword
  database: Minecraft
  port: 3306
  ip: 127.0.0.1

command-main: friends
command-aliases:
  - fr
  - friend

# Protection field where you can set the maximum amount of orders a player can send per minute.
# A player could start spamming a certain command like /fr add <user> which creates a new order
# every time, the process of sending a new request is quite big. So the player could crash the server
# or DDOS / DoS your MySQL server.
# >>>>>>>NEVER CHANGE THE ORDER OF THE ARRAY<<<<<<<
protection:
  SEND_NEW_REQUEST: 10 # UI & command.
  UPDATE_USER_SETTINGS: 10 # UI Only.
  BLOCK_PLAYER: 10 # UI & command.
  UNBLOCK_PLAYER: 10 # UI & command.
  ADD_FAVORITE: 10 # UI & command.
  REMOVE_FAVORITE: 10 # UI & command.
  REMOVE_FRIEND: 10 # UI & command.

# Note that whatever permission you put "PigFriends." will always be at the beginning.
# In this example, the permission will be PigFriends.permission.friends.
permission: permission.friends

# true = use a permission, false = don't use a permission.
use-permission: true

# The limit of friends that someone can have.
friend-limit: 10

# The amount of friends per page (message / UI)
friend-per-page: 10

# Request check delay (in seconds)
request-check-time: 2

# Task that checks any special state for certain actions (should be left at 1 second)
# This task mostly just sends messages to the players after performing certain tasks.
order-listener-task-time: 1

# Friendly fire (true = can hit friends, false = can't hit friends)
friendly-fire: true

# Soft-depends

# PigNotify Feature.
pig-notify: false

# Commando Feature (for registering sub-commands on client-side).
commando: false

# NEVER CHANGE THIS SETTING.
development: true